version: "3.7"

services:
  neuron:
    build: neuron
    command: jupyter lab --port=90 --ip=0.0.0.0 --allow-root --notebook-dir=/notebooks/
    environment:
      - HOME=home
    volumes:
      - ./notebooks:/notebooks
    ports:
      - "200:90"