#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/code/neuron"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/code/neuron/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/code/notebooks/x86_64/.libs/libnrnmech.so" "$@"
